eshop/backet/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = 'backet'

urlpatterns = [
    path('add-to-backet/<int:id>/<str:category>/' , views.add_basket , name='add-to-backet')
]

eshop/category/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
    path('' , views.test),
    path('laptops' , views.laptops_view ,  name='laptops'),
    path('laptop-info/<int:pk>/', views.LaptopDetailView.as_view(), name='laptop-detail'),
    path('search', views.search, name='search'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('category.urls')),
    path('backet/' , include('backet.urls' , namespace='backet')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()



from django.conf import settings

eshop/backet/models.py
from django.db import models
from category.models import Laptop
# Create your models here.


class Backet(models.Model):
    product  = models.ForeignKey(Laptop , on_delete=models.CASCADE)

    def __str__(self):
        return self.product

eshop/category/models.py
from django.db import models

# Create your models here.

CHOICE_CATEGORY  = (
    ('laptops' , 'Ноутбуки'),
    ('mobile_phones' , 'Телефоны'),
    ('tablet' , 'Планшеты'),
    ('source_details' , 'Комплектующие'),
    ('nau' , 'Наушники')
)



class Category(models.Model):
    name = models.CharField(max_length=100 ,  verbose_name= 'Категория'  , choices=CHOICE_CATEGORY)

    def __str__(self):
        return self.name


OPERATION_SYSTEM = (
    ('mac' , 'MacOS'),
    ('linux' , 'Linux'),
    ('windows' , 'Windows')
)

TYPE_MONITOR  = (
    ('glossy'  , 'Глянцевый'),
    ('matt'  , 'Матовый')
)

class Laptop(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE , default=1)
    model =  models.CharField(max_length=255 , verbose_name='Модель ноутбука' , default='i534')
    brand =  models.CharField(max_length=255 , verbose_name='Бренд ' , default='Apple')
    diagonal =  models.CharField(max_length=255 , verbose_name='Диагональ ' , default='12')
    oper_system =  models.CharField(max_length=255 , verbose_name='Операционная система' , choices=OPERATION_SYSTEM)
    oper_memory = models.IntegerField(verbose_name='ОЗУ' , default=16)
    type_monitor = models.CharField(max_length=255 , verbose_name='Тип экрана' , choices=TYPE_MONITOR)
    count_core = models.IntegerField(verbose_name='Количество ядер' , default=8)
    price = models.IntegerField(verbose_name='Цена' , default='50000')
    image = models.ImageField(upload_to='images/', blank=True, null=True ,  verbose_name='Картинка')

    def __str__(self):
        return 'Модель - {} Бренд - {}'.format(self.model , self.brand)

    def get_all(self):
        return Laptop.objects.all()

    def delete_all(self):
        return Laptop.objects.all().delete()

eshop/backet/views.py
from django.shortcuts import render
from django.http import HttpResponse
from category.models import Category , Laptop
from .models import Backet
# Create your views here.


def add_basket(request , id , category):
    list_category  = list(Category.objects.all())
    current_elem  = None
    category_front = None
    for  elem in list_category:
        if str(elem) == "Ноутбук":
           current_elem = Laptop.objects.get(id=id)
    Backet.objects.add(current_elem)
    # print(current_elem)
    return HttpResponse('asdasd')

eshop/category/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Laptop , Category
from django.views.generic import DetailView
# Create your views here.


all_categories = Category.objects.all()
category = None
def test(request):
    laptop_instance = Laptop()
    all_laptop = laptop_instance.get_all()
    # laptop_instance.delete_all()
    ctx = {}
    ctx['category_name'] = 'all'
    ctx['all_laptop'] = all_laptop
    print(all_laptop)
    return render(request , 'category/index.html' , ctx)


def laptops_view(request):
    ctx = {}
    all_laptops = Laptop.objects.all()
    all_categories = Category.objects.all()


    ctx['all_laptops'] = all_laptops
    ctx['category_name'] = 'laptops'
    ctx['all_categories'] = all_categories

    print(all_categories)
    for elem in all_categories:
        print(elem)
    # print(all_laptops)
    return render(request , 'category/laptops.html' , ctx)



class LaptopDetailView(DetailView):
    queryset = Laptop.objects.all()
    template_name = 'category/laptop_detail.html'

    def get_context_data(self, **kwargs):
        context = super(LaptopDetailView, self).get_context_data(**kwargs)
        context['category_name'] = 'laptops'
        context['all_categories'] = all_categories
        return context

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.save()
        return obj

MODEL_CHOICE  = {
    'laptops' : Laptop,
}


def search(request):
    ctx = {}
    category  = Category.objects.get(name= request.GET.get('category')).name
    if request.GET.get('to') == '' or request.GET.get('from') == '':
        all_search = MODEL_CHOICE[category].objects.all()
    else:
        all_search = MODEL_CHOICE[category].objects.all().filter(price__lt=request.GET.get('to') , price__gt=request.GET.get('from'))
    ctx['req_category'] =  request.GET.get('category')
    ctx['req_price_to'] = request.GET.get('to')
    ctx['req_price_from'] = request.GET.get('from')
    ctx['all_search'] = all_search
    ctx['all_categories'] = all_categories
    ctx['category_name'] = category
    return render(request , 'category/search.html' , ctx)

eshop/eshop/templates/category/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="page-wrapper">
    {% include "includes/header.html" with a=5%}
    {% include "includes/backet.html" %}

    <section class="content">
        <div class="container">
            {% block content %}
                <div class="home-page">
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                </div>
            {% endblock  %}
        </div>
    </section>
</div>
</body>
</html>

eshop/eshop/templates/category/item_product.html
{% load static %}
{% if object %}
    <div class="object-item">
        {% if object.image %}
        <img  src="{{ object.image.url }}" alt="">
        {% endif  %}
        <div class="desc-item-wrap">
            <div class="desc-item">
                <div class="info-item">
                    <p class="left">Бренд</p>
                    <p class="right">{{ object.brand }}</p>
                </div>
                <div class="info-item">
                    <p class="left" >Модель</p>
                    <p class="right">{{ object.model }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Операционная система</p>
                    <p class="right">{{ object.oper_system }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Оперативная память</p>
                    <p class="right">{{ object.oper_memory }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Тип экрана</p>
                    <p class="right">{{ object.type_monitor }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Кол-во ядер</p>
                    <p class="right">{{ object.count_core }}</p>
                </div>
                 <div class="btns">
                     <p class="price">{{ object.price }} грн</p>
                  <a data-id="{{ object.id }}" data-category = '{{ object.category }}' class="js-add-backet to_backet" href="{% url 'backet:add-to-backet' object.id object.category %}">купить</a>
                    <a href="">
                        <img class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
                    </a>
            </div>
         </div>
            <!--<div class="dostavka">-->
                <!--Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, in!-->
            <!--</div>-->
        </div>
    </div>
<div class="right-filters">
 {% include 'includes/filters.html' %}
</div>


{% endif %}


{% block extrascript  %}

<script>
    $(document).ready(function() {
        App.ajax.init();
    });

</script>
{% endblock  %}

 <!-- <p>Диагональ: {{ elem.diagonal }}</p>
                  <p>Операционная система : {{ elem.oper_system }}</p>
                  <p>Операционная память : {{ elem.oper_memory }}</p>
                  <p>Тип экрана : {{ elem.type_monitor }}</p>
                  <p>Кол-во ядер: {{ elem.count_core }}</p>
                  <p>Цена : {{ elem.price }} грн</p> -->

eshop/eshop/templates/category/laptop_detail.html
{% extends 'category/index.html' %}

{% block content %}
{% include 'category/item_product.html' with object=object %}

{% endblock %}

eshop/eshop/templates/category/laptops.html
{% extends 'category/index.html' %}

{% block content %}
{% if req_category %}
<h2>{{ req_category.get_name_display  }}</h2>
{% endif %}
    <h1>Ноутбуки</h1>
    <div class="content-wrap">
        <div class="container-flex">
          {% for elem in all_laptops %}
              <a class="item" href="{% url 'laptop-detail' elem.id %}">
                <div class="photo-wrap">
                    {% if elem.image %}
                        <div class="photo-item" style="background-image: url({{elem.image.url}})"></div>
                    {% endif %}
                  </div>
                  <div class="description">
                      <p class='key-text'> Модель: </p>
                      <p class="value-text"> {{ elem.model }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Бренд: </p>
                      <p class="value-text"> {{ elem.brand }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Цена: </p>
                      <p class="value-text"> {{ elem.price }}</p>
                  </div>
              </a>
          {% endfor %}
        </div>
    </select>
        {% if req_price_to and req_price_from %}
            {% include 'includes/filters.html' with all_categories=all_categories  req_price_to=req_price_to  req_price_from=req_price_from %}
         {% else  %}
                    {% include 'includes/filters.html' with all_categories=all_categories %}

        {% endif %}
    </div>
{% endblock  %}

eshop/eshop/templates/category/search.html
{% block content %}
    {% include 'category/laptops.html' with all_laptops=all_search req_price_to=req_price_to req_price_from=req_price_from %}
{% endblock %}

eshop/eshop/templates/includes/backet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="backet">
    <h2>Корзина</h2>
    <span class="count">0</span>
</div>

</body>
</html>

eshop/eshop/templates/includes/filters.html
<div class="right-bar">
    <form action="{% url 'search' %}" method="get">
        <p>Категория</p>
        <select name="category" id="">
            {% for category in all_categories %}
            <option value="{{ category }}">{{ category.get_name_display }}</option>
            {% endfor %}
        </select>
        <div class="price-filter">
            <p>Установите цену</p>
            <label for="">От</label>
            <input name="from" type="number">
            <label for="">До</label>
            <input name="to" type="number">
            <button>Поиск</button>
        </div>
    </form>

    {% if all_laptops|length == 0 %}
        <h2>К сожелению по вашему запросу ничего не найдено</h2>
    {% else  %}
        {% if req_price_to or req_price_from %}
        <h3>Все что мы смогли найти по вашему запросу</h3>
           Цена <span>от {{ req_price_from }}</span>  - <span>до {{ req_price_to }} </span>
        {% endif %}
    {% endif %}


</div>

eshop/eshop/templates/includes/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.min.css' %}">
<script src="{% static 'js/vendors.min.js' %}" ></script>
<script src="{% static 'js/app.min.js' %}" ></script>

{% block extrascript  %} {% endblock  %}

<header class="{% if className == 'header' %} {{ className }} {% endif %} " >
    <nav class="navigation">
        <a class="{% if category_name == 'all' %} active-tab {% endif %}" href="/">Все товары</a>
        <a class="{% if category_name == 'laptops' %} active-tab {% endif %}" href="{% url 'laptops' %}">Ноутбуки</a>
        <a class="{% if category_name == 'mobile_phones' %} active-tab {% endif %}"  href="">Телефоны</a>
        <a class="{% if category_name == 'tablet' %} active-tab {% endif %}" href="">Планшеты</a>
        <a class="{% if category_name == 'source_details' %} active-tab {% endif %}" href="">Комплектующие</a>
        <a class="{% if category_name == 'nau' %} active-tab {% endif %}" href="">Наушники</a>
        <a href="">Смарт часы</a>
    </nav>
</header>